### ISSUE TITLE
建议维护 CS-Notes

### ISSUE THREAD

**Issue by Triple-Z** [FlyAndNotDown/it-knowledge-collection#1]
额，为啥不直接参与维护 [CS-Notes][]。

[CS-Notes]: https://github.com/CyC2018/CS-Notes

**Comment by FlyAndNotDown** [comment]
想不到吧

**Comment by Triple-Z** [comment]
我觉得还是众人拾柴火焰高。与其大家都弄个自己的不如都集中起来维护一个仓库，这样其他人还能及时的发现其中的错误。
